# Generated by Django 5.2 on 2025-07-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataKlien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_klien', models.CharField(max_length=50)),
                ('nama_perusahaan', models.CharField(max_length=100)),
                ('daerah', models.TextField()),
                ('kategori_klien', models.CharField(choices=[('individu', 'Individu'), ('partai', 'Partai'), ('perusahaan', 'Perusahaan'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('no_telp', models.CharField(max_length=12)),
                ('dokumen_pendukung', models.FileField(blank=True, null=True, upload_to='dokumen_klien/')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
