# Generated by Django 5.2 on 2025-07-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataklien',
            name='jabatan',
            field=models.TextField(default='jabatan default'),
            preserve_default=False,
        ),
    ]
