# Generated by Django 5.2.3 on 2025-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataklien',
            name='dokumen_pendukung',
            field=models.FileField(blank=True, null=True, upload_to='dokumen_klien/'),
        ),
        migrations.AddField(
            model_name='dataklien',
            name='kategori_klien',
            field=models.CharField(choices=[('individu', 'Individu'), ('partai', 'Partai'), ('perusahaan', 'Perusahaan'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20),
        ),
        migrations.AddField(
            model_name='dataklien',
            name='no_telp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
