# Generated by Django 5.2.3 on 2025-06-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klien', '0002_dataklien_dokumen_pendukung_dataklien_kategori_klien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataklien',
            name='no_telp',
            field=models.CharField(max_length=12),
        ),
    ]
