# Generated by Django 5.2 on 2025-06-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedp',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
