# Generated by Django 5.2 on 2025-06-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0002_alter_invoicedp_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicefinal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='kwitansidp',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='kwitansifinal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
