# Generated by Django 5.2 on 2025-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0005_invoicedp_account_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedp',
            name='account_currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
