# Generated by Django 5.2 on 2025-06-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0006_alter_invoicedp_account_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefinal',
            name='account_currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicefinal',
            name='beneficiary_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicefinal',
            name='beneficiary_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicefinal',
            name='beneficiary_bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicefinal',
            name='beneficiary_bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicefinal',
            name='beneficiary_swift_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoicefinal',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
