# Generated by Django 5.2 on 2025-07-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0008_alter_proposaltemplatehistory_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=100, unique=True)),
                ('tanggal', models.DateField()),
                ('pihak_pertama', models.CharField(max_length=255)),
                ('pihak_kedua', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('file_bast', models.FileField(blank=True, null=True, upload_to='bast/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
