# Generated by Django 5.2 on 2025-07-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0009_bast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bast',
            old_name='pihak_kedua',
            new_name='alamat_pihak_pertama',
        ),
        migrations.RenameField(
            model_name='bast',
            old_name='pihak_pertama',
            new_name='jabatan_pihak_pertama',
        ),
        migrations.RenameField(
            model_name='bast',
            old_name='isi',
            new_name='tanggal_tertulis',
        ),
        migrations.RemoveField(
            model_name='bast',
            name='file_bast',
        ),
        migrations.AddField(
            model_name='bast',
            name='nama_pihak_pertama',
            field=models.CharField(default='default name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bast',
            name='nomor_addendum',
            field=models.CharField(default='nomor addendum', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bast',
            name='tanggal_addendum',
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
    ]
