# Generated by Django 5.2 on 2025-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0010_rename_pihak_kedua_bast_alamat_pihak_pertama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bast',
            name='alamat_pihak_kedua',
            field=models.CharField(default='alamat default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bast',
            name='jabatan_pihak_kedua',
            field=models.CharField(default='jabatan default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bast',
            name='judul_survei',
            field=models.CharField(default='judul default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bast',
            name='nama_pihak_kedua',
            field=models.CharField(default='nama default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bast',
            name='nilai_kontrak_angka',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bast',
            name='nilai_kontrak_tertulis',
            field=models.TextField(default='seribu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bast',
            name='nomor_spk',
            field=models.CharField(default='nomor spk default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bast',
            name='tanggal_spk',
            field=models.DateField(default='2025-07-25'),
            preserve_default=False,
        ),
    ]
