# Generated by Django 5.2 on 2025-07-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0011_bast_alamat_pihak_kedua_bast_jabatan_pihak_kedua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bast',
            name='doc_type',
            field=models.CharField(default='bast', max_length=50),
        ),
    ]
