# Generated by Django 5.1.4 on 2025-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0012_bast_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bast',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='bast/signed/'),
        ),
        migrations.AddField(
            model_name='bast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
