# Generated by Django 5.2 on 2025-07-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klien', '0001_initial'),
        ('souvenir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_survei', models.CharField(default='', max_length=255, unique=True)),
                ('jenis_survei', models.CharField(choices=[('Elektoral', 'Elektoral'), ('Tematik', 'Tematik')], default='Elektoral', max_length=50)),
                ('ruang_lingkup', models.CharField(choices=[('Nasional', 'Nasional'), ('Kabupaten/Kota', 'Kabupaten/Kota'), ('Dapil', 'Dapil'), ('Provinsi', 'Provinsi')], default='Nasional', max_length=50)),
                ('wilayah_survei', models.JSONField(blank=True, default=list)),
                ('tipe_survei', models.CharField(choices=[('Online', 'Online'), ('Tatap muka', 'Tatap muka'), ('Telepon', 'Telepon')], default='Paper-based', max_length=50)),
                ('jumlah_responden', models.IntegerField(default=0)),
                ('harga_survei', models.FloatField(default=0)),
                ('tanggal_spk', models.DateField(blank=True, null=True)),
                ('tanggal_ws', models.DateField(blank=True, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('milestone_1', models.DateField(blank=True, null=True)),
                ('milestone_2', models.DateField(blank=True, null=True)),
                ('milestone_3', models.DateField(blank=True, null=True)),
                ('ppk', models.JSONField(blank=True, default=list)),
                ('peneliti', models.JSONField(blank=True, default=list)),
                ('jumlah_souvenir', models.IntegerField(blank=True, default=0, null=True)),
                ('klien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survei_set', to='klien.dataklien')),
                ('souvenir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survei_dengan_souvenir', to='souvenir.souvenir')),
            ],
            options={
                'db_table': 'survei',
            },
        ),
    ]
