# Generated by Django 5.2 on 2025-07-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Kabupaten/Kota', 'Kabupaten/Kota'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi'), ('Dapil', 'Dapil')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Online', 'Online'), ('Telepon', 'Telepon'), ('Tatap muka', 'Tatap muka')], default='Paper-based', max_length=50),
        ),
    ]
