# Generated by Django 5.2 on 2025-07-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0002_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Nasional', 'Nasional'), ('Dapil', 'Dapil'), ('Kabupaten/Kota', 'Kabupaten/Kota'), ('Provinsi', 'Provinsi')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Telepon', 'Telepon'), ('Online', 'Online'), ('Tatap muka', 'Tatap muka')], default='Paper-based', max_length=50),
        ),
    ]
