# Generated by Django 5.2 on 2025-07-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0002_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Kota', 'Kota'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi')], default='Nasional', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Lainnya', 'Lainnya'), ('Paper-based', 'Paper-based')], default='Paper-based', max_length=255),
        ),
    ]
