# Generated by Django 5.2 on 2025-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0005_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AddField(
            model_name='survei',
            name='harga_survei_terbilang',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='nomor_spk',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Dapil', 'Dapil'), ('Kabupaten/Kota', 'Kabupaten/Kota')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Telepon', 'Telepon'), ('Online', 'Online'), ('Tatap muka', 'Tatap muka')], default='Paper-based', max_length=50),
        ),
    ]
