# Generated by Django 5.2 on 2025-07-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0006_survei_harga_survei_terbilang_survei_nomor_spk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Kabupaten/Kota', 'Kabupaten/Kota'), ('Provinsi', 'Provinsi'), ('Dapil', 'Dapil'), ('Nasional', 'Nasional')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Online', 'Online'), ('Telepon', 'Telepon'), ('Tatap muka', 'Tatap muka')], default='Paper-based', max_length=50),
        ),
    ]
