# Generated by Django 5.2 on 2025-07-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0007_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Nasional', 'Nasional'), ('Kabupaten/Kota', 'Kabupaten/Kota'), ('Provinsi', 'Provinsi'), ('Dapil', 'Dapil')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Online', 'Online'), ('Tatap muka', 'Tatap muka'), ('Telepon', 'Telepon')], default='Paper-based', max_length=50),
        ),
    ]
