# Generated by Django 5.1.1 on 2025-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0003_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Nasional', 'Nasional'), ('Kota', 'Kota'), ('Provinsi', 'Provinsi')], default='Nasional', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Lainnya', 'Lainnya'), ('Digital', 'Digital'), ('Paper-based', 'Paper-based')], default='Paper-based', max_length=255),
        ),
    ]
