# Generated by Django 4.2.16 on 2025-06-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('souvenir', '0001_initial'),
        ('survei', '0008_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survei',
            old_name='nama_survei',
            new_name='judul_survei',
        ),
        migrations.RemoveField(
            model_name='survei',
            name='waktu_berakhir_survei',
        ),
        migrations.RemoveField(
            model_name='survei',
            name='waktu_mulai_survei',
        ),
        migrations.AddField(
            model_name='survei',
            name='jenis_survei',
            field=models.CharField(choices=[('Elektoral', 'Elektoral'), ('Tematik', 'Tematik')], default='Elektoral', max_length=50),
        ),
        migrations.AddField(
            model_name='survei',
            name='milestone_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='milestone_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='milestone_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='souvenir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survei_dengan_souvenir', to='souvenir.souvenir'),
        ),
        migrations.AddField(
            model_name='survei',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='tanggal_spk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='tanggal_ws',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Kota', 'Kota'), ('Dapil', 'Dapil')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Online', 'Online'), ('Telepon', 'Telepon'), ('Tatap muka', 'Tatap muka')], default='Paper-based', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='wilayah_survei',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
