

# Generated by Django 5.2.3 on 2025-06-16 17:17



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0008_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',

            field=models.CharField(choices=[('Kota', 'Kota'), ('Provinsi', 'Provinsi'), ('Nasional', 'Nasional')], default='Nasional', max_length=255),


        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',

            field=models.CharField(choices=[('Digital', 'Digital'), ('Lainnya', 'Lainnya'), ('Paper-based', 'Paper-based')], default='Paper-based', max_length=255),

        ),
    ]
