# Generated by Django 5.1.4 on 2025-07-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0008_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Nasional', 'Nasional'), ('Provinsi', 'Provinsi'), ('Kabupaten/Kota', 'Kabupaten/Kota'), ('Dapil', 'Dapil')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Tatap muka', 'Tatap muka'), ('Online', 'Online'), ('Telepon', 'Telepon')], default='Paper-based', max_length=50),
        ),
    ]
