# Generated by Django 4.2.16 on 2025-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0009_rename_nama_survei_survei_judul_survei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Nasional', 'Nasional'), ('Dapil', 'Dapil'), ('Provinsi', 'Provinsi'), ('Kota', 'Kota')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Online', 'Online'), ('Tatap muka', 'Tatap muka'), ('Telepon', 'Telepon')], default='Paper-based', max_length=50),
        ),
    ]
