

# Generated by Django 5.2.3 on 2025-06-16 17:20



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [


        ('survei', '0009_rename_nama_survei_survei_judul_survei_and_more'),


    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Kota', 'Kota')], default='Nasional', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Paper-based', 'Paper-based'), ('Lainnya', 'Lainnya')], default='Paper-based', max_length=255),
        ),
    ]
