# Generated by Django 5.1.4 on 2025-07-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0009_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Dapil', 'Dapil'), ('Kabupaten/Kota', 'Kabupaten/Kota'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Telepon', 'Telepon'), ('Tatap muka', 'Tatap muka'), ('Online', 'Online')], default='Paper-based', max_length=50),
        ),
    ]
