

# Generated by Django 5.2.3 on 2025-06-16 17:35



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0010_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',

            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Kota', 'Kota'), ('Dapil', 'Dapil')], default='Nasional', max_length=50),

        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',

            field=models.CharField(choices=[('Online', 'Online'), ('Telepon', 'Telepon'), ('Tatap muka', 'Tatap muka')], default='Paper-based', max_length=50),

        ),
    ]
