# Generated by Django 5.2.3 on 2025-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0010_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Kota', 'Kota')], default='Nasional', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Paper-based', 'Paper-based'), ('Lainnya', 'Lainnya'), ('Digital', 'Digital')], default='Paper-based', max_length=255),
        ),
    ]
