# Generated by Django 5.2 on 2025-06-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0010_alter_survei_ruang_lingkup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Kota', 'Kota'), ('Nasional', 'Nasional')], default='Nasional', max_length=255),
        ),
    ]
