# Generated by Django 4.2.16 on 2025-07-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0011_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AddField(
            model_name='survei',
            name='peneliti',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='survei',
            name='ppk',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Kota', 'Kota'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi'), ('Dapil', 'Dapil')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Tatap muka', 'Tatap muka'), ('Telepon', 'Telepon'), ('Online', 'Online')], default='Paper-based', max_length=50),
        ),
    ]
