# Generated by Django 4.2.16 on 2025-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0012_survei_peneliti_survei_ppk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survei',
            name='jumlah_souvenir',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Nasional', 'Nasional'), ('Dapil', 'Dapil'), ('Kota', 'Kota'), ('Provinsi', 'Provinsi')], default='Nasional', max_length=50),
        ),
    ]
