# Generated by Django 5.2.3 on 2025-07-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0011_alter_survei_ruang_lingkup'),
        ('survei', '0013_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
        ('survei', '0015_alter_survei_tipe_survei'),
        ('survei', '0015_remove_survei_tanggal_spk_alter_survei_ruang_lingkup_and_more'),
    ]

    operations = [
    ]
