# Generated by Django 4.2.16 on 2025-07-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0016_merge_20250702_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='survei',
            name='tanggal_spk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Dapil', 'Dapil'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi'), ('Kabupaten/Kota', 'Kabupaten/Kota')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Telepon', 'Telepon'), ('Tatap muka', 'Tatap muka'), ('Online', 'Online')], default='Paper-based', max_length=50),
        ),
    ]
