# Generated by Django 5.1.1 on 2025-07-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0017_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Paper-based', 'Paper-based'), ('Lainnya', 'Lainnya'), ('Digital', 'Digital')], default='Paper-based', max_length=255),
        ),
    ]
