# Generated by Django 4.2.16 on 2025-07-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0017_survei_tanggal_spk_alter_survei_ruang_lingkup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Kabupaten/Kota', 'Kabupaten/Kota'), ('Dapil', 'Dapil'), ('Nasional', 'Nasional')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Tatap muka', 'Tatap muka'), ('Online', 'Online'), ('Telepon', 'Telepon')], default='Paper-based', max_length=50),
        ),
    ]
