# Generated by Django 5.2.3 on 2025-07-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0016_merge_20250702_1601'),
        ('survei', '0018_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
    ]
