# Generated by Django 5.2.3 on 2025-07-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0013_alter_survei_ruang_lingkup'),
        ('survei', '0017_alter_survei_tipe_survei'),
        ('survei', '0019_merge_20250704_0003'),
    ]

    operations = [
    ]
