# Generated by Django 5.1.2 on 2025-07-09 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenir', '0001_initial'),
        ('survei', '0019_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE survei
                SET wilayah_survei =
                    '"' || REPLACE(wilayah_survei, '"', '\\"') || '"'
                WHERE wilayah_survei IS NOT NULL
                AND wilayah_survei !~ '^\\[';  -- skip rows already JSON arrays
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RenameField(
            model_name='survei',
            old_name='nama_survei',
            new_name='judul_survei',
        ),
        migrations.RemoveField(
            model_name='survei',
            name='waktu_berakhir_survei',
        ),
        migrations.RemoveField(
            model_name='survei',
            name='waktu_mulai_survei',
        ),
        migrations.AddField(
            model_name='survei',
            name='jenis_survei',
            field=models.CharField(choices=[('Elektoral', 'Elektoral'), ('Tematik', 'Tematik')], default='Elektoral', max_length=50),
        ),
        migrations.AddField(
            model_name='survei',
            name='jumlah_souvenir',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='milestone_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='milestone_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='milestone_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='peneliti',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='survei',
            name='ppk',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='survei',
            name='souvenir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survei_dengan_souvenir', to='souvenir.souvenir'),
        ),
        migrations.AddField(
            model_name='survei',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='tanggal_spk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survei',
            name='tanggal_ws',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Nasional', 'Nasional'), ('Dapil', 'Dapil'), ('Provinsi', 'Provinsi'), ('Kabupaten/Kota', 'Kabupaten/Kota')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Telepon', 'Telepon'), ('Tatap muka', 'Tatap muka'), ('Online', 'Online')], default='Paper-based', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='wilayah_survei',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
