# Generated by Django 5.2.3 on 2025-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0020_merge_20250706_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Dapil', 'Dapil'), ('Nasional', 'Nasional'), ('Kabupaten/Kota', 'Kabupaten/Kota')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Online', 'Online'), ('Tatap muka', 'Tatap muka'), ('Telepon', 'Telepon')], default='Paper-based', max_length=50),
        ),
    ]
