# Generated by Django 5.2 on 2025-07-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_souvenir', models.CharField(default='', max_length=255, unique=True)),
                ('jumlah_stok', models.IntegerField(default=0)),
                ('jumlah_minimum', models.IntegerField(default=0)),
                ('kategori', models.CharField(choices=[('fisik', 'Fisik'), ('non-fisik', 'Non-Fisik')], default='fisik', max_length=20)),
                ('harga_per_pcs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('nama_vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('kontak_vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_order', models.DateField(blank=True, null=True)),
                ('tanggal_diterima', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
