# Generated by Django 4.2.16 on 2025-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='souvenir',
            name='harga_per_pcs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='kategori',
            field=models.CharField(choices=[('fisik', 'Fisik'), ('non-fisik', 'Non-Fisik')], default='fisik', max_length=20),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='kontak_vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='nama_vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='tanggal_diterima',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='tanggal_order',
            field=models.DateField(blank=True, null=True),
        ),
    ]
