# Generated by Django 5.2.3 on 2025-06-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_survei', models.CharField(choices=[('tematik', 'Tematik'), ('regular', 'Regular')], default='regular', help_text='Jenis survei untuk menentukan fitur milestone', max_length=50)),
                ('tanggal_spk', models.DateTimeField(blank=True, help_text='Tanggal deadline SPK', null=True)),
                ('tanggal_selesai_pekerjaan', models.DateTimeField(blank=True, help_text='Tanggal actual penyelesaian pekerjaan', null=True)),
            ],
        ),
    ]
