# Generated by Django 5.1.1 on 2025-06-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackersurvei',
            old_name='lakukan_survei',
            new_name='pra_survei',
        ),
        migrations.RenameField(
            model_name='trackersurvei',
            old_name='terima_info_survei',
            new_name='turun_lapangan',
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='pantau_responden',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
