# Generated by Django 5.2.3 on 2025-06-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0002_survei'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survei',
        ),
        migrations.AddField(
            model_name='trackersurvei',
            name='tanggal_selesai_pekerjaan',
            field=models.DateField(blank=True, help_text='Tanggal laporan diserahkan/pekerjaan selesai', null=True),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='ambil_souvenir',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='buat_invoice_dp',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='buat_invoice_final',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='buat_kontrak',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='lakukan_survei',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='pantau_data_cleaning',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='pantau_responden',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='pembayaran_dp',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='pembayaran_lunas',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='pembuatan_kwitansi_dp',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='pembuatan_kwitansi_final',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='pembuatan_laporan',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='penyerahan_laporan',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='terima_info_survei',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='terima_request_souvenir',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('FINISHED_WITH_DELAY', 'Finished with Delay'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
    ]
