# Generated by Django 5.1.1 on 2025-06-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0002_rename_lakukan_survei_trackersurvei_pra_survei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackersurvei',
            name='status_pantau_responden',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
    ]
