# Generated by Django 5.1.1 on 2025-06-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0003_trackersurvei_status_pantau_responden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackersurvei',
            name='pantau_data_cleaning',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed'), ('CLEANING', 'Cleaning in Progress'), ('DONE', 'Cleaned')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='pra_survei',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed'), ('PRE_TEST', 'Pre-Test'), ('SKIP_PRE_TEST', 'Tidak Perlu Pre-Test')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='status_pantau_responden',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='turun_lapangan',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed'), ('WORKSHOP', 'Workshop'), ('INPUT_DATA', 'Input Data')], default='NOT_STARTED', max_length=30),
        ),
    ]
