# Generated by Django 5.1.1 on 2025-07-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0004_alter_trackersurvei_pantau_data_cleaning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackersurvei',
            name='status_pantau_responden',
        ),
        migrations.AlterField(
            model_name='trackersurvei',
            name='pra_survei',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed'), ('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'Questionnare In Progress'), ('FINISHED', 'Questionnaire Finished'), ('PRE_TEST', 'Pre-Test'), ('SKIP_PRE_TEST', 'Tidak Perlu Pre-Test')], default='NOT_STARTED', max_length=30),
        ),
    ]
