# Generated by Django 5.1.1 on 2025-07-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0005_remove_trackersurvei_status_pantau_responden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackersurvei',
            name='pra_survei',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed'), ('PRE_TEST', 'Pre-Test'), ('SKIP_PRE_TEST', 'Tidak Perlu Pre-Test')], default='NOT_STARTED', max_length=30),
        ),
    ]
