# Generated by Django 5.1.1 on 2025-07-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0006_alter_trackersurvei_pra_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackersurvei',
            name='pantau_data_cleaning',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed'), ('CLEANING', 'Cleaning in Progress')], default='NOT_STARTED', max_length=30),
        ),
    ]
