# Generated by Django 5.1.2 on 2025-07-09 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0008_alter_trackersurvei_pra_survei'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackersurvei',
            name='cleaning_personil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        
        migrations.CreateModel(
            name='JumlahResponden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumlah_responden', to='tracker_survei.trackersurvei')),
            ],
            options={
                'db_table': 'jumlah_responden',
                'ordering': ['-updated_at'],
            },
        ),
    ]
